version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./backend
    depends_on:
      - mongo  
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:  
      - APP_PORT=80
      - APP_MONGO_URL=mongodb://mongo:27017/tfg
    ports: ['80:80'] 

  # db:
  #   container_name: db
  #   image: mongo:4.0
  #   restart: always
  #   ports: ['27017:27017']

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:  
      - VUE_APP_API_URL=http://localhost/api

volumes:
  dbdata: