version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./backend
    depends_on:
      - mongo  
    volumes:
      - ./backend:/usr/backend
      - /usr/backend/node_modules
    environment:  
      - APP_PORT=80
      - MONGO_URL=mongodb://mongo:27017/tfg
      - APP_FRONTEND=http://localhost
      - SECRET=au3o6b4ouiwbea65v78we65bva908W7456BV9874WA56BV987AW56BV987AW456BV9A78W45n978wa4
      - BASE_PASSWORD=1234
    ports: ['80:80']

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - '80:80'
  #   environment:  
  #     - VUE_APP_API_URL=http://localhost:3000/api

volumes:
  dbdata:

